title: "Avital's GH actions test repo"
description: "Site to test setting up GH actions and Jekyll from scratch"
repository: apinnick/gh-actions-test
baseurl: /gh-actions-test/

# docdir: documentation
type: website

plugins: [jekyll-asciidoc, jekyll-paginate, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging, jekyll-seo-tag]

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

asciidoc: {}
asciidoctor:
  attributes:
  - showtitle=@
  base_dir: public/
  safe: unsafe

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

exclude:
  - README.md
  - vendor
