title: "Avital's test repo for GH actions"
description: "This repo is a demo for publishing Asciidoc files with GH actions and Jekyll."
repository: apinnick/gh-actions-test
baseurl: /gh-actions-test/

# docdir: documentation
type: website

plugins: [jekyll-asciidoc, jekyll-paginate, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging, jekyll-seo-tag]

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

asciidoc: {}
asciidoctor:
  attributes:
  - showtitle=@
  - build=upstream
  - project-short=Forklift
  - project-full=Forklift
  - project-first=Forklift
  - project-version=2.0
  - virt=KubeVirt
  - ocp=OpenShift{nbsp}Kubernetes{nbsp}Engine
  - ocp-version=4.6
  - ocp-short=OKE
  - context=forklift
  safe: unsafe

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

exclude:
  - README.md
  - vendor
